# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/ztp/proto/v1/deviceztp_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/ztp/proto/v1/deviceztp_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.ztp.proto.v1 import deviceztp_custom_pb2 as edgelq__sdk_dot_ztp_dot_proto_dot_v1_dot_deviceztp__custom__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import client_pb2 as google_dot_api_dot_client__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from goten_sdk.types import view_pb2 as goten__sdk_dot_types_dot_view__pb2
from goten_sdk.types import watch_type_pb2 as goten__sdk_dot_types_dot_watch__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/edgelq-sdk/ztp/proto/v1/deviceztp_service.proto\x12\nntt.ztp.v1\x1a.edgelq-sdk/ztp/proto/v1/deviceztp_custom.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1agoten-sdk/types/view.proto\x1a goten-sdk/types/watch_type.proto2\xf5\x01\n\x10\x44\x65viceztpService\x12\xb3\x01\n\x1dZtpGetEdgeLQEndpointForDevice\x12\x30.ntt.ztp.v1.ZtpGetEdgeLQEndpointForDeviceRequest\x1a\x31.ntt.ztp.v1.ZtpGetEdgeLQEndpointForDeviceResponse\")\x82\xd3\xe4\x93\x02#\"!/v1:ztpGetEdgeLQEndpointForDevice(\x01\x30\x01\x1a+\xca\x41\x0eztp.edgelq.com\xd2\x41\x17https://apis.edgelq.comBu\n\x11\x63om.ntt.ztp.pb.v1B\x15\x44\x65viceztpServiceProtoP\x00ZGgithub.com/cloudwan/edgelq-sdk/ztp/client/v1/deviceztp;deviceztp_clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.ztp.proto.v1.deviceztp_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.ntt.ztp.pb.v1B\025DeviceztpServiceProtoP\000ZGgithub.com/cloudwan/edgelq-sdk/ztp/client/v1/deviceztp;deviceztp_client'
  _globals['_DEVICEZTPSERVICE']._loaded_options = None
  _globals['_DEVICEZTPSERVICE']._serialized_options = b'\312A\016ztp.edgelq.com\322A\027https://apis.edgelq.com'
  _globals['_DEVICEZTPSERVICE'].methods_by_name['ZtpGetEdgeLQEndpointForDevice']._loaded_options = None
  _globals['_DEVICEZTPSERVICE'].methods_by_name['ZtpGetEdgeLQEndpointForDevice']._serialized_options = b'\202\323\344\223\002#\"!/v1:ztpGetEdgeLQEndpointForDevice'
  _globals['_DEVICEZTPSERVICE']._serialized_start=325
  _globals['_DEVICEZTPSERVICE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
