from edgelq_sdk.iam.proto.v1 import attestation_custom_pb2 as _attestation_custom_pb2
from edgelq_sdk.iam.proto.v1 import attestation_domain_pb2 as _attestation_domain_pb2
from edgelq_sdk.iam.proto.v1 import attestation_domain_service_pb2 as _attestation_domain_service_pb2
from edgelq_sdk.iam.proto.v1 import attestation_service_pb2 as _attestation_service_pb2
from edgelq_sdk.iam.proto.v1 import authorization_custom_pb2 as _authorization_custom_pb2
from edgelq_sdk.iam.proto.v1 import authorization_service_pb2 as _authorization_service_pb2
from edgelq_sdk.iam.proto.v1 import condition_pb2 as _condition_pb2
from edgelq_sdk.iam.proto.v1 import condition_service_pb2 as _condition_service_pb2
from edgelq_sdk.iam.proto.v1 import group_pb2 as _group_pb2
from edgelq_sdk.iam.proto.v1 import group_member_pb2 as _group_member_pb2
from edgelq_sdk.iam.proto.v1 import group_member_service_pb2 as _group_member_service_pb2
from edgelq_sdk.iam.proto.v1 import group_service_pb2 as _group_service_pb2
from edgelq_sdk.iam.proto.v1 import member_assignment_pb2 as _member_assignment_pb2
from edgelq_sdk.iam.proto.v1 import member_assignment_service_pb2 as _member_assignment_service_pb2
from edgelq_sdk.iam.proto.v1 import organization_pb2 as _organization_pb2
from edgelq_sdk.iam.proto.v1 import organization_custom_pb2 as _organization_custom_pb2
from edgelq_sdk.iam.proto.v1 import organization_invitation_pb2 as _organization_invitation_pb2
from edgelq_sdk.iam.proto.v1 import organization_invitation_custom_pb2 as _organization_invitation_custom_pb2
from edgelq_sdk.iam.proto.v1 import organization_invitation_service_pb2 as _organization_invitation_service_pb2
from edgelq_sdk.iam.proto.v1 import organization_service_pb2 as _organization_service_pb2
from edgelq_sdk.iam.proto.v1 import permission_pb2 as _permission_pb2
from edgelq_sdk.iam.proto.v1 import permission_service_pb2 as _permission_service_pb2
from edgelq_sdk.iam.proto.v1 import project_pb2 as _project_pb2
from edgelq_sdk.iam.proto.v1 import project_custom_pb2 as _project_custom_pb2
from edgelq_sdk.iam.proto.v1 import project_invitation_pb2 as _project_invitation_pb2
from edgelq_sdk.iam.proto.v1 import project_invitation_custom_pb2 as _project_invitation_custom_pb2
from edgelq_sdk.iam.proto.v1 import project_invitation_service_pb2 as _project_invitation_service_pb2
from edgelq_sdk.iam.proto.v1 import project_service_pb2 as _project_service_pb2
from edgelq_sdk.iam.proto.v1 import role_pb2 as _role_pb2
from edgelq_sdk.iam.proto.v1 import role_binding_pb2 as _role_binding_pb2
from edgelq_sdk.iam.proto.v1 import role_binding_service_pb2 as _role_binding_service_pb2
from edgelq_sdk.iam.proto.v1 import role_service_pb2 as _role_service_pb2
from edgelq_sdk.iam.proto.v1 import service_account_pb2 as _service_account_pb2
from edgelq_sdk.iam.proto.v1 import service_account_key_pb2 as _service_account_key_pb2
from edgelq_sdk.iam.proto.v1 import service_account_key_service_pb2 as _service_account_key_service_pb2
from edgelq_sdk.iam.proto.v1 import service_account_service_pb2 as _service_account_service_pb2
from edgelq_sdk.iam.proto.v1 import service_projects_management_custom_pb2 as _service_projects_management_custom_pb2
from edgelq_sdk.iam.proto.v1 import service_projects_management_service_pb2 as _service_projects_management_service_pb2
from edgelq_sdk.iam.proto.v1 import user_pb2 as _user_pb2
from edgelq_sdk.iam.proto.v1 import user_custom_pb2 as _user_custom_pb2
from edgelq_sdk.iam.proto.v1 import user_service_pb2 as _user_service_pb2
from google.api import annotations_pb2 as _annotations_pb2
from google.api import client_pb2 as _client_pb2
from google.protobuf import empty_pb2 as _empty_pb2
from goten_sdk.meta_service.proto.v1 import meta_pb2 as _meta_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
