# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/iam/proto/v1/project.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/iam/proto/v1/project.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.iam.proto.v1 import common_pb2 as edgelq__sdk_dot_iam_dot_proto_dot_v1_dot_common__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from goten_sdk.types import meta_pb2 as goten__sdk_dot_types_dot_meta__pb2
from goten_sdk.types import multi_region_policy_pb2 as goten__sdk_dot_types_dot_multi__region__policy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%edgelq-sdk/iam/proto/v1/project.proto\x12\nntt.iam.v1\x1a$edgelq-sdk/iam/proto/v1/common.proto\x1a\x19google/api/resource.proto\x1a\x1agoten-sdk/types/meta.proto\x1a)goten-sdk/types/multi_region_policy.proto\"\xce\x04\n\x07Project\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x08metadata\x18\x06 \x01(\x0b\x32\x11.goten.types.Meta\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\r \x01(\t\x12\x1b\n\x13parent_organization\x18\x03 \x01(\t\x12;\n\x13multi_region_policy\x18\x07 \x01(\x0b\x32\x1e.goten.types.MultiRegionPolicy\x12\x18\n\x10\x65nabled_services\x18\x08 \x03(\t\x12/\n\rbusiness_tier\x18\t \x01(\x0e\x32\x18.ntt.iam.v1.BusinessTier\x12\x36\n\rservice_tiers\x18\n \x03(\x0b\x32\x1f.ntt.iam.v1.ServiceBusinessTier\x12\x19\n\x11root_organization\x18\x04 \x01(\t\x12\x15\n\rancestry_path\x18\x05 \x03(\t\x12>\n\x0eservice_errors\x18\x0b \x03(\x0b\x32&.ntt.iam.v1.Project.ServiceErrorsEntry\x12\x1b\n\x13services_generation\x18\x0c \x01(\x03\x1aO\n\x12ServiceErrorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.ntt.iam.v1.ServiceErrors:\x02\x38\x01:/\xea\x41,\n\x16iam.edgelq.com/Project\x12\x12projects/{project}Bd\n\x11\x63om.ntt.iam.pb.v1B\x0cProjectProtoP\x01Z?github.com/cloudwan/edgelq-sdk/iam/resources/v1/project;projectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.iam.proto.v1.project_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.ntt.iam.pb.v1B\014ProjectProtoP\001Z?github.com/cloudwan/edgelq-sdk/iam/resources/v1/project;project'
  _globals['_PROJECT_SERVICEERRORSENTRY']._loaded_options = None
  _globals['_PROJECT_SERVICEERRORSENTRY']._serialized_options = b'8\001'
  _globals['_PROJECT']._loaded_options = None
  _globals['_PROJECT']._serialized_options = b'\352A,\n\026iam.edgelq.com/Project\022\022projects/{project}'
  _globals['_PROJECT']._serialized_start=190
  _globals['_PROJECT']._serialized_end=780
  _globals['_PROJECT_SERVICEERRORSENTRY']._serialized_start=652
  _globals['_PROJECT_SERVICEERRORSENTRY']._serialized_end=731
# @@protoc_insertion_point(module_scope)
