# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/limits/proto/v1/common.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/limits/proto/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goten_sdk.meta_service.proto.v1 import resource_pb2 as goten__sdk_dot_meta__service_dot_proto_dot_v1_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'edgelq-sdk/limits/proto/v1/common.proto\x12\rntt.limits.v1\x1a.goten-sdk/meta-service/proto/v1/resource.proto\"O\n\x16RegionalPlanAssignment\x12\x0c\n\x04plan\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x17\n\x0fplan_generation\x18\x03 \x01(\x03\"<\n\tAllowance\x12\x10\n\x08resource\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\x12\x0e\n\x06region\x18\x03 \x01(\tBg\n\x14\x63om.ntt.limits.pb.v1B\x0b\x43ommonProtoP\x01Z@github.com/cloudwan/edgelq-sdk/limits/resources/v1/common;commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.limits.proto.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.ntt.limits.pb.v1B\013CommonProtoP\001Z@github.com/cloudwan/edgelq-sdk/limits/resources/v1/common;common'
  _globals['_REGIONALPLANASSIGNMENT']._serialized_start=106
  _globals['_REGIONALPLANASSIGNMENT']._serialized_end=185
  _globals['_ALLOWANCE']._serialized_start=187
  _globals['_ALLOWANCE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
