# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/iam/proto/v1alpha2/role.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/iam/proto/v1alpha2/role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.iam.proto.v1alpha2 import condition_pb2 as edgelq__sdk_dot_iam_dot_proto_dot_v1alpha2_dot_condition__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from goten_sdk.types import meta_pb2 as goten__sdk_dot_types_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(edgelq-sdk/iam/proto/v1alpha2/role.proto\x12\x10ntt.iam.v1alpha2\x1a-edgelq-sdk/iam/proto/v1alpha2/condition.proto\x1a\x19google/api/resource.proto\x1a\x1agoten-sdk/types/meta.proto\"\xe3\x02\n\x04Role\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12-\n\x14included_permissions\x18\x03 \x03(\tB\x0f\xfa\x41\x0c\n\nPermission\x12\x45\n\x19\x64\x65\x66\x61ult_condition_binding\x18\x05 \x01(\x0b\x32\".ntt.iam.v1alpha2.ConditionBinding\x12G\n\x1bincluded_condition_bindings\x18\x06 \x03(\x0b\x32\".ntt.iam.v1alpha2.ConditionBinding\x12+\n\x13required_conditions\x18\x07 \x03(\tB\x0e\xfa\x41\x0b\n\tCondition\x12#\n\x08metadata\x18\x04 \x01(\x0b\x32\x11.goten.types.Meta:&\xea\x41#\n\x13iam.edgelq.com/Role\x12\x0croles/{role}Bg\n\x17\x63om.ntt.iam.pb.v1alpha2B\tRoleProtoP\x01Z?github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/role;roleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.iam.proto.v1alpha2.role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.ntt.iam.pb.v1alpha2B\tRoleProtoP\001Z?github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/role;role'
  _globals['_ROLE'].fields_by_name['included_permissions']._loaded_options = None
  _globals['_ROLE'].fields_by_name['included_permissions']._serialized_options = b'\372A\014\n\nPermission'
  _globals['_ROLE'].fields_by_name['required_conditions']._loaded_options = None
  _globals['_ROLE'].fields_by_name['required_conditions']._serialized_options = b'\372A\013\n\tCondition'
  _globals['_ROLE']._loaded_options = None
  _globals['_ROLE']._serialized_options = b'\352A#\n\023iam.edgelq.com/Role\022\014roles/{role}'
  _globals['_ROLE']._serialized_start=165
  _globals['_ROLE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
