# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/monitoring/proto/v4/alert.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/monitoring/proto/v4/alert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.monitoring.proto.v4 import common_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_common__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from goten_sdk.types import meta_pb2 as goten__sdk_dot_types_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*edgelq-sdk/monitoring/proto/v4/alert.proto\x12\x11ntt.monitoring.v4\x1a+edgelq-sdk/monitoring/proto/v4/common.proto\x1a\x19google/api/resource.proto\x1a\x1agoten-sdk/types/meta.proto\"\xf1\x07\n\x05\x41lert\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x08metadata\x18\x02 \x01(\x0b\x32\x11.goten.types.Meta\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12+\n\x04info\x18\x04 \x01(\x0b\x32\x1d.ntt.monitoring.v4.Alert.Info\x12-\n\x05state\x18\x05 \x01(\x0b\x32\x1e.ntt.monitoring.v4.Alert.State\x1a\xcd\x03\n\x04Info\x12;\n\ntime_serie\x18\x01 \x01(\x0b\x32\'.ntt.monitoring.v4.Alert.Info.TimeSerie\x12\x45\n\x0fobserved_values\x18\x02 \x01(\x0b\x32,.ntt.monitoring.v4.Alert.Info.ObservedValues\x1a\x93\x01\n\tTimeSerie\x12\x0b\n\x03key\x18\x65 \x01(\x0c\x12)\n\x06metric\x18\x01 \x01(\x0b\x32\x19.ntt.monitoring.v4.Metric\x12@\n\x12monitored_resource\x18\x02 \x01(\x0b\x32$.ntt.monitoring.v4.MonitoredResource\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\x1a\xaa\x01\n\x0eObservedValues\x12\x15\n\rexample_value\x18\x01 \x01(\x01\x12O\n\nper_metric\x18\x02 \x03(\x0b\x32;.ntt.monitoring.v4.Alert.Info.ObservedValues.PerMetricEntry\x1a\x30\n\x0ePerMetricEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a\xcf\x01\n\x05State\x12\x11\n\tis_firing\x18\x02 \x01(\x08\x12\x17\n\x0fis_acknowledged\x18\x03 \x01(\x08\x12\x13\n\x0bis_silenced\x18\x04 \x01(\x08\x12.\n\x08lifetime\x18\x07 \x01(\x0b\x32\x1c.ntt.monitoring.v4.TimeRange\x12\x1a\n\x12needs_notification\x18\x08 \x01(\x08\x12\x1c\n\x14notification_created\x18\t \x01(\x08\x12\x1b\n\x13lifecycle_completed\x18\n \x01(\x08:\xa0\x01\xea\x41\x9c\x01\n\x1bmonitoring.edgelq.com/Alert\x12}projects/{project}/regions/{region}/alertingPolicies/{alerting_policy}/alertingConditions/{alerting_condition}/alerts/{alert}Bl\n\x18\x63om.ntt.monitoring.pb.v4B\nAlertProtoP\x01ZBgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/alert;alertb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.monitoring.proto.v4.alert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.ntt.monitoring.pb.v4B\nAlertProtoP\001ZBgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/alert;alert'
  _globals['_ALERT_INFO_OBSERVEDVALUES_PERMETRICENTRY']._loaded_options = None
  _globals['_ALERT_INFO_OBSERVEDVALUES_PERMETRICENTRY']._serialized_options = b'8\001'
  _globals['_ALERT']._loaded_options = None
  _globals['_ALERT']._serialized_options = b'\352A\234\001\n\033monitoring.edgelq.com/Alert\022}projects/{project}/regions/{region}/alertingPolicies/{alerting_policy}/alertingConditions/{alerting_condition}/alerts/{alert}'
  _globals['_ALERT']._serialized_start=166
  _globals['_ALERT']._serialized_end=1175
  _globals['_ALERT_INFO']._serialized_start=341
  _globals['_ALERT_INFO']._serialized_end=802
  _globals['_ALERT_INFO_TIMESERIE']._serialized_start=482
  _globals['_ALERT_INFO_TIMESERIE']._serialized_end=629
  _globals['_ALERT_INFO_OBSERVEDVALUES']._serialized_start=632
  _globals['_ALERT_INFO_OBSERVEDVALUES']._serialized_end=802
  _globals['_ALERT_INFO_OBSERVEDVALUES_PERMETRICENTRY']._serialized_start=754
  _globals['_ALERT_INFO_OBSERVEDVALUES_PERMETRICENTRY']._serialized_end=802
  _globals['_ALERT_STATE']._serialized_start=805
  _globals['_ALERT_STATE']._serialized_end=1012
# @@protoc_insertion_point(module_scope)
