# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/monitoring/proto/v4/alert_change.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/monitoring/proto/v4/alert_change.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.monitoring.proto.v4 import alert_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_alert__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1edgelq-sdk/monitoring/proto/v4/alert_change.proto\x12\x11ntt.monitoring.v4\x1a*edgelq-sdk/monitoring/proto/v4/alert.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\"\xd2\x04\n\x0b\x41lertChange\x12\x35\n\x05\x61\x64\x64\x65\x64\x18\x01 \x01(\x0b\x32$.ntt.monitoring.v4.AlertChange.AddedH\x00\x12;\n\x08modified\x18\x02 \x01(\x0b\x32\'.ntt.monitoring.v4.AlertChange.ModifiedH\x00\x12\x39\n\x07\x63urrent\x18\x04 \x01(\x0b\x32&.ntt.monitoring.v4.AlertChange.CurrentH\x00\x12\x39\n\x07removed\x18\x03 \x01(\x0b\x32&.ntt.monitoring.v4.AlertChange.RemovedH\x00\x1a\x44\n\x05\x41\x64\x64\x65\x64\x12\'\n\x05\x61lert\x18\x01 \x01(\x0b\x32\x18.ntt.monitoring.v4.Alert\x12\x12\n\nview_index\x18\x02 \x01(\x05\x1a\xa2\x01\n\x08Modified\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x05\x61lert\x18\x02 \x01(\x0b\x32\x18.ntt.monitoring.v4.Alert\x12.\n\nfield_mask\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\x12\x1b\n\x13previous_view_index\x18\x04 \x01(\x05\x12\x12\n\nview_index\x18\x05 \x01(\x05\x1a\x32\n\x07\x43urrent\x12\'\n\x05\x61lert\x18\x01 \x01(\x0b\x32\x18.ntt.monitoring.v4.Alert\x1a+\n\x07Removed\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nview_index\x18\x02 \x01(\x05\x42\r\n\x0b\x63hange_typeBr\n\x18\x63om.ntt.monitoring.pb.v4B\x10\x41lertChangeProtoP\x00ZBgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/alert;alertb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.monitoring.proto.v4.alert_change_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.ntt.monitoring.pb.v4B\020AlertChangeProtoP\000ZBgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/alert;alert'
  _globals['_ALERTCHANGE']._serialized_start=178
  _globals['_ALERTCHANGE']._serialized_end=772
  _globals['_ALERTCHANGE_ADDED']._serialized_start=427
  _globals['_ALERTCHANGE_ADDED']._serialized_end=495
  _globals['_ALERTCHANGE_MODIFIED']._serialized_start=498
  _globals['_ALERTCHANGE_MODIFIED']._serialized_end=660
  _globals['_ALERTCHANGE_CURRENT']._serialized_start=662
  _globals['_ALERTCHANGE_CURRENT']._serialized_end=712
  _globals['_ALERTCHANGE_REMOVED']._serialized_start=714
  _globals['_ALERTCHANGE_REMOVED']._serialized_end=757
# @@protoc_insertion_point(module_scope)
