# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/monitoring/proto/v4/bucket.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/monitoring/proto/v4/bucket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from goten_sdk.types import meta_pb2 as goten__sdk_dot_types_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+edgelq-sdk/monitoring/proto/v4/bucket.proto\x12\x11ntt.monitoring.v4\x1a\x19google/api/resource.proto\x1a\x1agoten-sdk/types/meta.proto\"\xdf\x05\n\x06\x42ucket\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x08metadata\x18\x02 \x01(\x0b\x32\x11.goten.types.Meta\x12>\n\x07metrics\x18\x03 \x03(\x0b\x32-.ntt.monitoring.v4.Bucket.RequiredTypedLabels\x12@\n\tresources\x18\x04 \x03(\x0b\x32-.ntt.monitoring.v4.Bucket.RequiredTypedLabels\x12J\n\x10required_alt_kvs\x18\x05 \x03(\x0b\x32\x30.ntt.monitoring.v4.Bucket.ResolvedKeysWithValues\x1a-\n\x0eResolvedValues\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x0e\n\x06values\x18\x02 \x03(\x03\x1aX\n\x16ResolvedKeysWithValues\x12>\n\x0cresolved_kvs\x18\x01 \x03(\x0b\x32(.ntt.monitoring.v4.Bucket.ResolvedValues\x1a\xf1\x01\n\x13RequiredTypedLabels\x12\r\n\x05types\x18\x01 \x03(\t\x12I\n\x06labels\x18\x02 \x03(\x0b\x32\x39.ntt.monitoring.v4.Bucket.RequiredTypedLabels.LabelsEntry\x1a\x64\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.ntt.monitoring.v4.Bucket.RequiredTypedLabels.Strings:\x02\x38\x01\x1a\x1a\n\x07Strings\x12\x0f\n\x07strings\x18\x01 \x03(\t:W\xea\x41T\n\x1cmonitoring.edgelq.com/Bucket\x12\x34projects/{project}/regions/{region}/buckets/{bucket}Bo\n\x18\x63om.ntt.monitoring.pb.v4B\x0b\x42ucketProtoP\x01ZDgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/bucket;bucketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.monitoring.proto.v4.bucket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.ntt.monitoring.pb.v4B\013BucketProtoP\001ZDgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/bucket;bucket'
  _globals['_BUCKET_REQUIREDTYPEDLABELS_LABELSENTRY']._loaded_options = None
  _globals['_BUCKET_REQUIREDTYPEDLABELS_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_BUCKET']._loaded_options = None
  _globals['_BUCKET']._serialized_options = b'\352AT\n\034monitoring.edgelq.com/Bucket\0224projects/{project}/regions/{region}/buckets/{bucket}'
  _globals['_BUCKET']._serialized_start=122
  _globals['_BUCKET']._serialized_end=857
  _globals['_BUCKET_RESOLVEDVALUES']._serialized_start=389
  _globals['_BUCKET_RESOLVEDVALUES']._serialized_end=434
  _globals['_BUCKET_RESOLVEDKEYSWITHVALUES']._serialized_start=436
  _globals['_BUCKET_RESOLVEDKEYSWITHVALUES']._serialized_end=524
  _globals['_BUCKET_REQUIREDTYPEDLABELS']._serialized_start=527
  _globals['_BUCKET_REQUIREDTYPEDLABELS']._serialized_end=768
  _globals['_BUCKET_REQUIREDTYPEDLABELS_LABELSENTRY']._serialized_start=640
  _globals['_BUCKET_REQUIREDTYPEDLABELS_LABELSENTRY']._serialized_end=740
  _globals['_BUCKET_REQUIREDTYPEDLABELS_STRINGS']._serialized_start=742
  _globals['_BUCKET_REQUIREDTYPEDLABELS_STRINGS']._serialized_end=768
# @@protoc_insertion_point(module_scope)
