# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/monitoring/proto/v4/monitored_resource_descriptor.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/monitoring/proto/v4/monitored_resource_descriptor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.monitoring.proto.v4 import common_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_common__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from goten_sdk.types import meta_pb2 as goten__sdk_dot_types_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBedgelq-sdk/monitoring/proto/v4/monitored_resource_descriptor.proto\x12\x11ntt.monitoring.v4\x1a+edgelq-sdk/monitoring/proto/v4/common.proto\x1a\x19google/api/resource.proto\x1a\x1agoten-sdk/types/meta.proto\"\x89\x03\n\x1bMonitoredResourceDescriptor\x12\x0c\n\x04name\x18\x05 \x01(\t\x12#\n\x08metadata\x18! \x01(\x0b\x32\x11.goten.types.Meta\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x32\n\x06labels\x18\x04 \x03(\x0b\x32\".ntt.monitoring.v4.LabelDescriptor\x12?\n\x17promoted_label_key_sets\x18  \x03(\x0b\x32\x1e.ntt.monitoring.v4.LabelKeySet:\x88\x01\xea\x41\x84\x01\n1monitoring.edgelq.com/MonitoredResourceDescriptor\x12Oservices/{service}/monitoredResourceDescriptors/{monitored_resource_descriptor}B\xb2\x01\n\x18\x63om.ntt.monitoring.pb.v4B MonitoredResourceDescriptorProtoP\x01Zrgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/monitored_resource_descriptor;monitored_resource_descriptorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.monitoring.proto.v4.monitored_resource_descriptor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.ntt.monitoring.pb.v4B MonitoredResourceDescriptorProtoP\001Zrgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/monitored_resource_descriptor;monitored_resource_descriptor'
  _globals['_MONITOREDRESOURCEDESCRIPTOR']._loaded_options = None
  _globals['_MONITOREDRESOURCEDESCRIPTOR']._serialized_options = b'\352A\204\001\n1monitoring.edgelq.com/MonitoredResourceDescriptor\022Oservices/{service}/monitoredResourceDescriptors/{monitored_resource_descriptor}'
  _globals['_MONITOREDRESOURCEDESCRIPTOR']._serialized_start=190
  _globals['_MONITOREDRESOURCEDESCRIPTOR']._serialized_end=583
# @@protoc_insertion_point(module_scope)
