# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgelq_sdk.monitoring.proto.v4 import phantom_time_serie_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2
from edgelq_sdk.monitoring.proto.v4 import phantom_time_serie_service_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edgelq_sdk/monitoring/proto/v4/phantom_time_serie_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhantomTimeSerieServiceStub(object):
    """PhantomTimeSerie service API for Monitoring
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPhantomTimeSerie = channel.unary_unary(
                '/ntt.monitoring.v4.PhantomTimeSerieService/GetPhantomTimeSerie',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.GetPhantomTimeSerieRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.FromString,
                _registered_method=True)
        self.BatchGetPhantomTimeSeries = channel.unary_unary(
                '/ntt.monitoring.v4.PhantomTimeSerieService/BatchGetPhantomTimeSeries',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.BatchGetPhantomTimeSeriesRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.BatchGetPhantomTimeSeriesResponse.FromString,
                _registered_method=True)
        self.ListPhantomTimeSeries = channel.unary_unary(
                '/ntt.monitoring.v4.PhantomTimeSerieService/ListPhantomTimeSeries',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.ListPhantomTimeSeriesRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.ListPhantomTimeSeriesResponse.FromString,
                _registered_method=True)
        self.WatchPhantomTimeSerie = channel.unary_stream(
                '/ntt.monitoring.v4.PhantomTimeSerieService/WatchPhantomTimeSerie',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSerieRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSerieResponse.FromString,
                _registered_method=True)
        self.WatchPhantomTimeSeries = channel.unary_stream(
                '/ntt.monitoring.v4.PhantomTimeSerieService/WatchPhantomTimeSeries',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSeriesRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSeriesResponse.FromString,
                _registered_method=True)
        self.CreatePhantomTimeSerie = channel.unary_unary(
                '/ntt.monitoring.v4.PhantomTimeSerieService/CreatePhantomTimeSerie',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.CreatePhantomTimeSerieRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.FromString,
                _registered_method=True)
        self.UpdatePhantomTimeSerie = channel.unary_unary(
                '/ntt.monitoring.v4.PhantomTimeSerieService/UpdatePhantomTimeSerie',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.UpdatePhantomTimeSerieRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.FromString,
                _registered_method=True)
        self.DeletePhantomTimeSerie = channel.unary_unary(
                '/ntt.monitoring.v4.PhantomTimeSerieService/DeletePhantomTimeSerie',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.DeletePhantomTimeSerieRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PhantomTimeSerieServiceServicer(object):
    """PhantomTimeSerie service API for Monitoring
    """

    def GetPhantomTimeSerie(self, request, context):
        """GetPhantomTimeSerie
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetPhantomTimeSeries(self, request, context):
        """BatchGetPhantomTimeSeries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPhantomTimeSeries(self, request, context):
        """ListPhantomTimeSeries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchPhantomTimeSerie(self, request, context):
        """WatchPhantomTimeSerie
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchPhantomTimeSeries(self, request, context):
        """WatchPhantomTimeSeries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePhantomTimeSerie(self, request, context):
        """CreatePhantomTimeSerie
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePhantomTimeSerie(self, request, context):
        """UpdatePhantomTimeSerie
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePhantomTimeSerie(self, request, context):
        """DeletePhantomTimeSerie
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhantomTimeSerieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPhantomTimeSerie': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPhantomTimeSerie,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.GetPhantomTimeSerieRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.SerializeToString,
            ),
            'BatchGetPhantomTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetPhantomTimeSeries,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.BatchGetPhantomTimeSeriesRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.BatchGetPhantomTimeSeriesResponse.SerializeToString,
            ),
            'ListPhantomTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPhantomTimeSeries,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.ListPhantomTimeSeriesRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.ListPhantomTimeSeriesResponse.SerializeToString,
            ),
            'WatchPhantomTimeSerie': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchPhantomTimeSerie,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSerieRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSerieResponse.SerializeToString,
            ),
            'WatchPhantomTimeSeries': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchPhantomTimeSeries,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSeriesRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSeriesResponse.SerializeToString,
            ),
            'CreatePhantomTimeSerie': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePhantomTimeSerie,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.CreatePhantomTimeSerieRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.SerializeToString,
            ),
            'UpdatePhantomTimeSerie': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePhantomTimeSerie,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.UpdatePhantomTimeSerieRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.SerializeToString,
            ),
            'DeletePhantomTimeSerie': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePhantomTimeSerie,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.DeletePhantomTimeSerieRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ntt.monitoring.v4.PhantomTimeSerieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ntt.monitoring.v4.PhantomTimeSerieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhantomTimeSerieService(object):
    """PhantomTimeSerie service API for Monitoring
    """

    @staticmethod
    def GetPhantomTimeSerie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.PhantomTimeSerieService/GetPhantomTimeSerie',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.GetPhantomTimeSerieRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetPhantomTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.PhantomTimeSerieService/BatchGetPhantomTimeSeries',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.BatchGetPhantomTimeSeriesRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.BatchGetPhantomTimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPhantomTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.PhantomTimeSerieService/ListPhantomTimeSeries',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.ListPhantomTimeSeriesRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.ListPhantomTimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchPhantomTimeSerie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ntt.monitoring.v4.PhantomTimeSerieService/WatchPhantomTimeSerie',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSerieRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSerieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchPhantomTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ntt.monitoring.v4.PhantomTimeSerieService/WatchPhantomTimeSeries',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSeriesRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.WatchPhantomTimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePhantomTimeSerie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.PhantomTimeSerieService/CreatePhantomTimeSerie',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.CreatePhantomTimeSerieRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePhantomTimeSerie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.PhantomTimeSerieService/UpdatePhantomTimeSerie',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.UpdatePhantomTimeSerieRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__pb2.PhantomTimeSerie.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePhantomTimeSerie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.PhantomTimeSerieService/DeletePhantomTimeSerie',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_phantom__time__serie__service__pb2.DeletePhantomTimeSerieRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
