# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/monitoring/proto/v4/recovery_store_sharding_info_change.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/monitoring/proto/v4/recovery_store_sharding_info_change.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.monitoring.proto.v4 import recovery_store_sharding_info_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_recovery__store__sharding__info__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHedgelq-sdk/monitoring/proto/v4/recovery_store_sharding_info_change.proto\x12\x11ntt.monitoring.v4\x1a\x41\x65\x64gelq-sdk/monitoring/proto/v4/recovery_store_sharding_info.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\"\xb7\x06\n\x1fRecoveryStoreShardingInfoChange\x12I\n\x05\x61\x64\x64\x65\x64\x18\x01 \x01(\x0b\x32\x38.ntt.monitoring.v4.RecoveryStoreShardingInfoChange.AddedH\x00\x12O\n\x08modified\x18\x02 \x01(\x0b\x32;.ntt.monitoring.v4.RecoveryStoreShardingInfoChange.ModifiedH\x00\x12M\n\x07\x63urrent\x18\x04 \x01(\x0b\x32:.ntt.monitoring.v4.RecoveryStoreShardingInfoChange.CurrentH\x00\x12M\n\x07removed\x18\x03 \x01(\x0b\x32:.ntt.monitoring.v4.RecoveryStoreShardingInfoChange.RemovedH\x00\x1ao\n\x05\x41\x64\x64\x65\x64\x12R\n\x1crecovery_store_sharding_info\x18\x01 \x01(\x0b\x32,.ntt.monitoring.v4.RecoveryStoreShardingInfo\x12\x12\n\nview_index\x18\x02 \x01(\x05\x1a\xcd\x01\n\x08Modified\x12\x0c\n\x04name\x18\x01 \x01(\t\x12R\n\x1crecovery_store_sharding_info\x18\x02 \x01(\x0b\x32,.ntt.monitoring.v4.RecoveryStoreShardingInfo\x12.\n\nfield_mask\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\x12\x1b\n\x13previous_view_index\x18\x04 \x01(\x05\x12\x12\n\nview_index\x18\x05 \x01(\x05\x1a]\n\x07\x43urrent\x12R\n\x1crecovery_store_sharding_info\x18\x01 \x01(\x0b\x32,.ntt.monitoring.v4.RecoveryStoreShardingInfo\x1a+\n\x07Removed\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nview_index\x18\x02 \x01(\x05\x42\r\n\x0b\x63hange_typeB\xb4\x01\n\x18\x63om.ntt.monitoring.pb.v4B$RecoveryStoreShardingInfoChangeProtoP\x00Zpgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/recovery_store_sharding_info;recovery_store_sharding_infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.monitoring.proto.v4.recovery_store_sharding_info_change_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.ntt.monitoring.pb.v4B$RecoveryStoreShardingInfoChangeProtoP\000Zpgithub.com/cloudwan/edgelq-sdk/monitoring/resources/v4/recovery_store_sharding_info;recovery_store_sharding_info'
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE']._serialized_start=224
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE']._serialized_end=1047
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE_ADDED']._serialized_start=573
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE_ADDED']._serialized_end=684
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE_MODIFIED']._serialized_start=687
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE_MODIFIED']._serialized_end=892
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE_CURRENT']._serialized_start=894
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE_CURRENT']._serialized_end=987
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE_REMOVED']._serialized_start=989
  _globals['_RECOVERYSTORESHARDINGINFOCHANGE_REMOVED']._serialized_end=1032
# @@protoc_insertion_point(module_scope)
