# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgelq_sdk.monitoring.proto.v4 import time_serie_custom_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edgelq_sdk/monitoring/proto/v4/time_serie_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TimeSerieServiceStub(object):
    """TimeSerie service API for Monitoring
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTimeSeries = channel.unary_unary(
                '/ntt.monitoring.v4.TimeSerieService/ListTimeSeries',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.ListTimeSeriesRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.ListTimeSeriesResponse.FromString,
                _registered_method=True)
        self.QueryProjectTimeSeriesStats = channel.unary_unary(
                '/ntt.monitoring.v4.TimeSerieService/QueryProjectTimeSeriesStats',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryProjectTimeSeriesStatsRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryProjectTimeSeriesStatsResponse.FromString,
                _registered_method=True)
        self.QueryServiceTimeSeriesStats = channel.unary_unary(
                '/ntt.monitoring.v4.TimeSerieService/QueryServiceTimeSeriesStats',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryServiceTimeSeriesStatsRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryServiceTimeSeriesStatsResponse.FromString,
                _registered_method=True)
        self.CreateTimeSeries = channel.unary_unary(
                '/ntt.monitoring.v4.TimeSerieService/CreateTimeSeries',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.CreateTimeSeriesRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.CreateTimeSeriesResponse.FromString,
                _registered_method=True)
        self.WatchTimeSeries = channel.unary_stream(
                '/ntt.monitoring.v4.TimeSerieService/WatchTimeSeries',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.WatchTimeSeriesRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.WatchTimeSeriesResponse.FromString,
                _registered_method=True)


class TimeSerieServiceServicer(object):
    """TimeSerie service API for Monitoring
    """

    def ListTimeSeries(self, request, context):
        """ListTimeSeries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryProjectTimeSeriesStats(self, request, context):
        """QueryProjectTimeSeriesStats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryServiceTimeSeriesStats(self, request, context):
        """QueryServiceTimeSeriesStats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTimeSeries(self, request, context):
        """CreateTimeSeries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTimeSeries(self, request, context):
        """WatchTimeSeries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeSerieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTimeSeries,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.ListTimeSeriesRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.ListTimeSeriesResponse.SerializeToString,
            ),
            'QueryProjectTimeSeriesStats': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryProjectTimeSeriesStats,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryProjectTimeSeriesStatsRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryProjectTimeSeriesStatsResponse.SerializeToString,
            ),
            'QueryServiceTimeSeriesStats': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryServiceTimeSeriesStats,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryServiceTimeSeriesStatsRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryServiceTimeSeriesStatsResponse.SerializeToString,
            ),
            'CreateTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTimeSeries,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.CreateTimeSeriesRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.CreateTimeSeriesResponse.SerializeToString,
            ),
            'WatchTimeSeries': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTimeSeries,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.WatchTimeSeriesRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.WatchTimeSeriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ntt.monitoring.v4.TimeSerieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ntt.monitoring.v4.TimeSerieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TimeSerieService(object):
    """TimeSerie service API for Monitoring
    """

    @staticmethod
    def ListTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.TimeSerieService/ListTimeSeries',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.ListTimeSeriesRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.ListTimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryProjectTimeSeriesStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.TimeSerieService/QueryProjectTimeSeriesStats',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryProjectTimeSeriesStatsRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryProjectTimeSeriesStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryServiceTimeSeriesStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.TimeSerieService/QueryServiceTimeSeriesStats',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryServiceTimeSeriesStatsRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.QueryServiceTimeSeriesStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v4.TimeSerieService/CreateTimeSeries',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.CreateTimeSeriesRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.CreateTimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ntt.monitoring.v4.TimeSerieService/WatchTimeSeries',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.WatchTimeSeriesRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v4_dot_time__serie__custom__pb2.WatchTimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
