# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgelq_sdk.monitoring.proto.v3 import alerting_condition_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2
from edgelq_sdk.monitoring.proto.v3 import alerting_condition_service_pb2 as edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edgelq_sdk/monitoring/proto/v3/alerting_condition_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlertingConditionServiceStub(object):
    """AlertingCondition service API for Monitoring
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAlertingCondition = channel.unary_unary(
                '/ntt.monitoring.v3.AlertingConditionService/GetAlertingCondition',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.GetAlertingConditionRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.FromString,
                _registered_method=True)
        self.BatchGetAlertingConditions = channel.unary_unary(
                '/ntt.monitoring.v3.AlertingConditionService/BatchGetAlertingConditions',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.BatchGetAlertingConditionsRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.BatchGetAlertingConditionsResponse.FromString,
                _registered_method=True)
        self.ListAlertingConditions = channel.unary_unary(
                '/ntt.monitoring.v3.AlertingConditionService/ListAlertingConditions',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.ListAlertingConditionsRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.ListAlertingConditionsResponse.FromString,
                _registered_method=True)
        self.WatchAlertingCondition = channel.unary_stream(
                '/ntt.monitoring.v3.AlertingConditionService/WatchAlertingCondition',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionResponse.FromString,
                _registered_method=True)
        self.WatchAlertingConditions = channel.unary_stream(
                '/ntt.monitoring.v3.AlertingConditionService/WatchAlertingConditions',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionsRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionsResponse.FromString,
                _registered_method=True)
        self.CreateAlertingCondition = channel.unary_unary(
                '/ntt.monitoring.v3.AlertingConditionService/CreateAlertingCondition',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.CreateAlertingConditionRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.FromString,
                _registered_method=True)
        self.UpdateAlertingCondition = channel.unary_unary(
                '/ntt.monitoring.v3.AlertingConditionService/UpdateAlertingCondition',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.UpdateAlertingConditionRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.FromString,
                _registered_method=True)
        self.DeleteAlertingCondition = channel.unary_unary(
                '/ntt.monitoring.v3.AlertingConditionService/DeleteAlertingCondition',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.DeleteAlertingConditionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SearchAlertingConditions = channel.unary_unary(
                '/ntt.monitoring.v3.AlertingConditionService/SearchAlertingConditions',
                request_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.SearchAlertingConditionsRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.SearchAlertingConditionsResponse.FromString,
                _registered_method=True)


class AlertingConditionServiceServicer(object):
    """AlertingCondition service API for Monitoring
    """

    def GetAlertingCondition(self, request, context):
        """GetAlertingCondition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetAlertingConditions(self, request, context):
        """BatchGetAlertingConditions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAlertingConditions(self, request, context):
        """ListAlertingConditions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAlertingCondition(self, request, context):
        """WatchAlertingCondition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAlertingConditions(self, request, context):
        """WatchAlertingConditions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAlertingCondition(self, request, context):
        """CreateAlertingCondition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAlertingCondition(self, request, context):
        """UpdateAlertingCondition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAlertingCondition(self, request, context):
        """DeleteAlertingCondition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchAlertingConditions(self, request, context):
        """SearchAlertingConditions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertingConditionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAlertingCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlertingCondition,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.GetAlertingConditionRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.SerializeToString,
            ),
            'BatchGetAlertingConditions': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetAlertingConditions,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.BatchGetAlertingConditionsRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.BatchGetAlertingConditionsResponse.SerializeToString,
            ),
            'ListAlertingConditions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAlertingConditions,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.ListAlertingConditionsRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.ListAlertingConditionsResponse.SerializeToString,
            ),
            'WatchAlertingCondition': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAlertingCondition,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionResponse.SerializeToString,
            ),
            'WatchAlertingConditions': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAlertingConditions,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionsRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionsResponse.SerializeToString,
            ),
            'CreateAlertingCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlertingCondition,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.CreateAlertingConditionRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.SerializeToString,
            ),
            'UpdateAlertingCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAlertingCondition,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.UpdateAlertingConditionRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.SerializeToString,
            ),
            'DeleteAlertingCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAlertingCondition,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.DeleteAlertingConditionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SearchAlertingConditions': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchAlertingConditions,
                    request_deserializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.SearchAlertingConditionsRequest.FromString,
                    response_serializer=edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.SearchAlertingConditionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ntt.monitoring.v3.AlertingConditionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ntt.monitoring.v3.AlertingConditionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlertingConditionService(object):
    """AlertingCondition service API for Monitoring
    """

    @staticmethod
    def GetAlertingCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/GetAlertingCondition',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.GetAlertingConditionRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetAlertingConditions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/BatchGetAlertingConditions',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.BatchGetAlertingConditionsRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.BatchGetAlertingConditionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAlertingConditions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/ListAlertingConditions',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.ListAlertingConditionsRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.ListAlertingConditionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchAlertingCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/WatchAlertingCondition',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchAlertingConditions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/WatchAlertingConditions',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionsRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.WatchAlertingConditionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAlertingCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/CreateAlertingCondition',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.CreateAlertingConditionRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAlertingCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/UpdateAlertingCondition',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.UpdateAlertingConditionRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__pb2.AlertingCondition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAlertingCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/DeleteAlertingCondition',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.DeleteAlertingConditionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchAlertingConditions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ntt.monitoring.v3.AlertingConditionService/SearchAlertingConditions',
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.SearchAlertingConditionsRequest.SerializeToString,
            edgelq__sdk_dot_monitoring_dot_proto_dot_v3_dot_alerting__condition__service__pb2.SearchAlertingConditionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
