# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/devices/proto/v1/customized_image_custom.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/devices/proto/v1/customized_image_custom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.devices.proto.v1 import customized_image_pb2 as edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_customized__image__pb2
from edgelq_sdk.devices.proto.v1 import customized_image_change_pb2 as edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_customized__image__change__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9edgelq-sdk/devices/proto/v1/customized_image_custom.proto\x12\x0entt.devices.v1\x1a\x32\x65\x64gelq-sdk/devices/proto/v1/customized_image.proto\x1a\x39\x65\x64gelq-sdk/devices/proto/v1/customized_image_change.proto\"!\n\x11RequestUrlRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\x12RequestUrlResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07headers\x18\x02 \x03(\tB\x90\x01\n\x15\x63om.ntt.devices.pb.v1B\x1a\x43ustomizedImageCustomProtoP\x00ZYgithub.com/cloudwan/edgelq-sdk/devices/client/v1/customized_image;customized_image_clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.devices.proto.v1.customized_image_custom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.ntt.devices.pb.v1B\032CustomizedImageCustomProtoP\000ZYgithub.com/cloudwan/edgelq-sdk/devices/client/v1/customized_image;customized_image_client'
  _globals['_REQUESTURLREQUEST']._serialized_start=188
  _globals['_REQUESTURLREQUEST']._serialized_end=221
  _globals['_REQUESTURLRESPONSE']._serialized_start=223
  _globals['_REQUESTURLRESPONSE']._serialized_end=273
# @@protoc_insertion_point(module_scope)
