# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgelq-sdk/devices/proto/v1/provisioning_approval_request_custom.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'edgelq-sdk/devices/proto/v1/provisioning_approval_request_custom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgelq_sdk.devices.proto.v1 import device_pb2 as edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_device__pb2
from edgelq_sdk.devices.proto.v1 import provisioning_approval_request_pb2 as edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_provisioning__approval__request__pb2
from edgelq_sdk.devices.proto.v1 import provisioning_approval_request_change_pb2 as edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_provisioning__approval__request__change__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFedgelq-sdk/devices/proto/v1/provisioning_approval_request_custom.proto\x12\x0entt.devices.v1\x1a(edgelq-sdk/devices/proto/v1/device.proto\x1a?edgelq-sdk/devices/proto/v1/provisioning_approval_request.proto\x1a\x46\x65\x64gelq-sdk/devices/proto/v1/provisioning_approval_request_change.proto\"n\n(ProvisionDeviceForApprovedRequestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\rdevice_status\x18\x02 \x01(\x0b\x32\x1d.ntt.devices.v1.Device.Status\"S\n)ProvisionDeviceForApprovedRequestResponse\x12&\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x16.ntt.devices.v1.DeviceB\xb6\x01\n\x15\x63om.ntt.devices.pb.v1B&ProvisioningApprovalRequestCustomProtoP\x00Zsgithub.com/cloudwan/edgelq-sdk/devices/client/v1/provisioning_approval_request;provisioning_approval_request_clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgelq_sdk.devices.proto.v1.provisioning_approval_request_custom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.ntt.devices.pb.v1B&ProvisioningApprovalRequestCustomProtoP\000Zsgithub.com/cloudwan/edgelq-sdk/devices/client/v1/provisioning_approval_request;provisioning_approval_request_client'
  _globals['_PROVISIONDEVICEFORAPPROVEDREQUESTREQUEST']._serialized_start=269
  _globals['_PROVISIONDEVICEFORAPPROVEDREQUESTREQUEST']._serialized_end=379
  _globals['_PROVISIONDEVICEFORAPPROVEDREQUESTRESPONSE']._serialized_start=381
  _globals['_PROVISIONDEVICEFORAPPROVEDREQUESTRESPONSE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
