# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgelq_sdk.devices.proto.v1 import ztp_provision_hardware_custom_pb2 as edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_ztp__provision__hardware__custom__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edgelq_sdk/devices/proto/v1/ztp_provision_hardware_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZtpProvisionHardwareServiceStub(object):
    """ZtpProvisionHardware service API for Devices
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProvisionHardware = channel.stream_stream(
                '/ntt.devices.v1.ZtpProvisionHardwareService/ProvisionHardware',
                request_serializer=edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_ztp__provision__hardware__custom__pb2.ProvisionHardwareRequest.SerializeToString,
                response_deserializer=edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_ztp__provision__hardware__custom__pb2.ProvisionHardwareResponse.FromString,
                _registered_method=True)


class ZtpProvisionHardwareServiceServicer(object):
    """ZtpProvisionHardware service API for Devices
    """

    def ProvisionHardware(self, request_iterator, context):
        """ProvisionHardware
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZtpProvisionHardwareServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProvisionHardware': grpc.stream_stream_rpc_method_handler(
                    servicer.ProvisionHardware,
                    request_deserializer=edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_ztp__provision__hardware__custom__pb2.ProvisionHardwareRequest.FromString,
                    response_serializer=edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_ztp__provision__hardware__custom__pb2.ProvisionHardwareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ntt.devices.v1.ZtpProvisionHardwareService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ntt.devices.v1.ZtpProvisionHardwareService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZtpProvisionHardwareService(object):
    """ZtpProvisionHardware service API for Devices
    """

    @staticmethod
    def ProvisionHardware(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ntt.devices.v1.ZtpProvisionHardwareService/ProvisionHardware',
            edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_ztp__provision__hardware__custom__pb2.ProvisionHardwareRequest.SerializeToString,
            edgelq__sdk_dot_devices_dot_proto_dot_v1_dot_ztp__provision__hardware__custom__pb2.ProvisionHardwareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
